export const COUNTRIES_DATA = [
  // Asia & South Asia
  { name: "India",           iso: "in", code: "+91",  phoneMaxLength: 10 },
  { name: "China",           iso: "cn", code: "+86",  phoneMaxLength: 11 },
  { name: "Japan",           iso: "jp", code: "+81",  phoneMaxLength: 10 },
  { name: "South Korea",     iso: "kr", code: "+82",  phoneMaxLength: 10 },
  { name: "Pakistan",        iso: "pk", code: "+92",  phoneMaxLength: 10 },
  { name: "Bangladesh",      iso: "bd", code: "+880", phoneMaxLength: 10 },
  { name: "Philippines",     iso: "ph", code: "+63",  phoneMaxLength: 10 },
  { name: "Indonesia",       iso: "id", code: "+62",  phoneMaxLength: 12 },
  { name: "Malaysia",        iso: "my", code: "+60",  phoneMaxLength: 10 },
  { name: "Singapore",       iso: "sg", code: "+65",  phoneMaxLength: 8  },
  { name: "Thailand",        iso: "th", code: "+66",  phoneMaxLength: 9  },
  { name: "Vietnam",         iso: "vn", code: "+84",  phoneMaxLength: 9  },
  { name: "Myanmar",         iso: "mm", code: "+95",  phoneMaxLength: 9  },
  { name: "Nepal",           iso: "np", code: "+977", phoneMaxLength: 10 },
  { name: "Sri Lanka",       iso: "lk", code: "+94",  phoneMaxLength: 9  },
  { name: "Afghanistan",     iso: "af", code: "+93",  phoneMaxLength: 9  },
  { name: "Cambodia",        iso: "kh", code: "+855", phoneMaxLength: 9  },
  { name: "Taiwan",          iso: "tw", code: "+886", phoneMaxLength: 9  },
  { name: "Hong Kong",       iso: "hk", code: "+852", phoneMaxLength: 8  },
  // Middle East
  { name: "UAE",             iso: "ae", code: "+971", phoneMaxLength: 9  },
  { name: "Saudi Arabia",    iso: "sa", code: "+966", phoneMaxLength: 9  },
  { name: "Israel",          iso: "il", code: "+972", phoneMaxLength: 9  },
  { name: "Turkey",          iso: "tr", code: "+90",  phoneMaxLength: 10 },
  { name: "Iran",            iso: "ir", code: "+98",  phoneMaxLength: 10 },
  { name: "Iraq",            iso: "iq", code: "+964", phoneMaxLength: 10 },
  { name: "Jordan",          iso: "jo", code: "+962", phoneMaxLength: 9  },
  { name: "Lebanon",         iso: "lb", code: "+961", phoneMaxLength: 8  },
  { name: "Kuwait",          iso: "kw", code: "+965", phoneMaxLength: 8  },
  { name: "Qatar",           iso: "qa", code: "+974", phoneMaxLength: 8  },
  { name: "Bahrain",         iso: "bh", code: "+973", phoneMaxLength: 8  },
  { name: "Oman",            iso: "om", code: "+968", phoneMaxLength: 8  },
  // Europe
  { name: "United Kingdom",  iso: "gb", code: "+44",  phoneMaxLength: 10 },
  { name: "Germany",         iso: "de", code: "+49",  phoneMaxLength: 11 },
  { name: "France",          iso: "fr", code: "+33",  phoneMaxLength: 9  },
  { name: "Italy",           iso: "it", code: "+39",  phoneMaxLength: 10 },
  { name: "Spain",           iso: "es", code: "+34",  phoneMaxLength: 9  },
  { name: "Portugal",        iso: "pt", code: "+351", phoneMaxLength: 9  },
  { name: "Netherlands",     iso: "nl", code: "+31",  phoneMaxLength: 9  },
  { name: "Belgium",         iso: "be", code: "+32",  phoneMaxLength: 9  },
  { name: "Switzerland",     iso: "ch", code: "+41",  phoneMaxLength: 9  },
  { name: "Sweden",          iso: "se", code: "+46",  phoneMaxLength: 9  },
  { name: "Norway",          iso: "no", code: "+47",  phoneMaxLength: 8  },
  { name: "Denmark",         iso: "dk", code: "+45",  phoneMaxLength: 8  },
  { name: "Finland",         iso: "fi", code: "+358", phoneMaxLength: 9  },
  { name: "Poland",          iso: "pl", code: "+48",  phoneMaxLength: 9  },
  { name: "Ukraine",         iso: "ua", code: "+380", phoneMaxLength: 9  },
  { name: "Russia",          iso: "ru", code: "+7",   phoneMaxLength: 10 },
  { name: "Romania",         iso: "ro", code: "+40",  phoneMaxLength: 9  },
  { name: "Greece",          iso: "gr", code: "+30",  phoneMaxLength: 10 },
  { name: "Czech Republic",  iso: "cz", code: "+420", phoneMaxLength: 9  },
  { name: "Hungary",         iso: "hu", code: "+36",  phoneMaxLength: 9  },
  { name: "Austria",         iso: "at", code: "+43",  phoneMaxLength: 10 },
  { name: "Ireland",         iso: "ie", code: "+353", phoneMaxLength: 9  },
  // Americas
  { name: "United States",   iso: "us", code: "+1",   phoneMaxLength: 10 },
  { name: "Canada",          iso: "ca", code: "+1",   phoneMaxLength: 10 },
  { name: "Mexico",          iso: "mx", code: "+52",  phoneMaxLength: 10 },
  { name: "Brazil",          iso: "br", code: "+55",  phoneMaxLength: 11 },
  { name: "Argentina",       iso: "ar", code: "+54",  phoneMaxLength: 10 },
  { name: "Colombia",        iso: "co", code: "+57",  phoneMaxLength: 10 },
  { name: "Chile",           iso: "cl", code: "+56",  phoneMaxLength: 9  },
  { name: "Peru",            iso: "pe", code: "+51",  phoneMaxLength: 9  },
  { name: "Venezuela",       iso: "ve", code: "+58",  phoneMaxLength: 10 },
  { name: "Ecuador",         iso: "ec", code: "+593", phoneMaxLength: 9  },
  { name: "Bolivia",         iso: "bo", code: "+591", phoneMaxLength: 8  },
  { name: "Paraguay",        iso: "py", code: "+595", phoneMaxLength: 9  },
  { name: "Uruguay",         iso: "uy", code: "+598", phoneMaxLength: 8  },
  // Oceania
  { name: "Australia",       iso: "au", code: "+61",  phoneMaxLength: 9  },
  { name: "New Zealand",     iso: "nz", code: "+64",  phoneMaxLength: 9  },
  // Africa
  { name: "Nigeria",         iso: "ng", code: "+234", phoneMaxLength: 10 },
  { name: "Egypt",           iso: "eg", code: "+20",  phoneMaxLength: 10 },
  { name: "South Africa",    iso: "za", code: "+27",  phoneMaxLength: 9  },
  { name: "Kenya",           iso: "ke", code: "+254", phoneMaxLength: 9  },
  { name: "Ethiopia",        iso: "et", code: "+251", phoneMaxLength: 9  },
  { name: "Ghana",           iso: "gh", code: "+233", phoneMaxLength: 9  },
  { name: "Tanzania",        iso: "tz", code: "+255", phoneMaxLength: 9  },
  { name: "Uganda",          iso: "ug", code: "+256", phoneMaxLength: 9  },
  { name: "Morocco",         iso: "ma", code: "+212", phoneMaxLength: 9  },
  { name: "Algeria",         iso: "dz", code: "+213", phoneMaxLength: 9  },
  { name: "Cameroon",        iso: "cm", code: "+237", phoneMaxLength: 9  },
  { name: "Ivory Coast",     iso: "ci", code: "+225", phoneMaxLength: 10 },
  { name: "Senegal",         iso: "sn", code: "+221", phoneMaxLength: 9  },
  { name: "Rwanda",          iso: "rw", code: "+250", phoneMaxLength: 9  },
  { name: "Zimbabwe",        iso: "zw", code: "+263", phoneMaxLength: 9  },
  { name: "Zambia",          iso: "zm", code: "+260", phoneMaxLength: 9  },
].sort((a, b) => a.name.localeCompare(b.name));

/** Curated skill suggestions shown in Primary & Secondary autocomplete. */
export const SKILL_OPTIONS = [
  // Programming & Frameworks
  "Python", "JavaScript", "TypeScript", "React", "Node.js",
  "Angular", "Vue.js", "Next.js", "Svelte", "Flutter",
  "Swift", "Kotlin", "Java", "C++", "C#", "Go", "Rust", "Ruby", "PHP",
  "Django", "FastAPI", "Spring Boot", "GraphQL", "REST API",
  // Data & Databases
  "SQL", "MongoDB", "PostgreSQL", "Redis", "Firebase", "Supabase", "Prisma",
  "Machine Learning", "Data Analysis", "Data Visualization",
  "Excel", "PowerBI", "Tableau", "R", "MATLAB",
  "TensorFlow", "PyTorch", "OpenAI API", "LangChain", "Prompt Engineering",
  "Data Engineering", "Apache Spark", "Hadoop", "dbt", "Snowflake", "BigQuery",
  // Design & Creative
  "UX Design", "UI Design", "Figma", "Adobe XD", "Sketch",
  "Graphic Design", "Video Editing", "Motion Graphics", "Illustration",
  "Adobe Photoshop", "Adobe Illustrator", "Adobe Premiere", "Canva",
  "Blender", "3D Modelling", "Brand Design", "Presentation Design",
  // Writing & Content
  "Content Writing", "Copywriting", "SEO", "Social Media", "Email Marketing",
  "Technical Writing", "Grant Writing", "Academic Writing",
  "Research", "Market Research", "Competitive Analysis",
  "Podcast Production", "Community Management", "Influencer Marketing",
  // Marketing & Ads
  "Google Ads", "Meta Ads", "LinkedIn Ads",
  "A/B Testing", "Conversion Optimization", "Funnel Design",
  // Project Management & Productivity
  "Project Management", "Scrum", "Agile", "JIRA", "Asana",
  "Power Automate", "Notion", "Slack Integration", "Zapier",
  "Pitch Deck", "Investor Relations",
  // Business & Finance
  "Financial Modelling", "Accounting", "Business Analysis",
  "Supply Chain", "Procurement", "E-commerce", "Dropshipping",
  "Shopify", "WooCommerce", "SAP", "ERP Systems",
  "Bookkeeping", "Tax Consulting", "Payroll",
  // QA & Testing
  "Quality Assurance", "Automation Testing", "Selenium",
  // Translation & Support
  "Translation", "Transcription", "Proofreading",
  "Customer Support", "CRM", "Salesforce",
  // DevOps & Cloud
  "DevOps", "Docker", "Kubernetes", "CI/CD",
  "AWS Lambda", "GCP Functions", "Azure DevOps",
  "Terraform", "Ansible", "Linux", "Bash Scripting",
  // Security
  "Cybersecurity", "Penetration Testing", "Cloud (AWS)", "Cloud (GCP)", "Cloud (Azure)",
  "OWASP", "Bug Bounty", "Network Security", "Web Scraping",
  // Education & Legal
  "Corporate Training", "Instructional Design", "Curriculum Development", "IELTS Tutoring",
  "Mediation", "Contract Drafting", "IP Law", "GDPR Compliance",
  "ISO Certification", "Risk Management", "ESG Reporting",
].sort();

export const TIMEZONES = [
  "Asia/Kolkata (IST +5:30)",
  "Asia/Dhaka (BST +6:00)",
  "Asia/Karachi (PKT +5:00)",
  "Asia/Colombo (SLST +5:30)",
  "Asia/Kathmandu (NPT +5:45)",
  "Asia/Tokyo (JST +9:00)",
  "Asia/Seoul (KST +9:00)",
  "Asia/Singapore (SGT +8:00)",
  "Asia/Shanghai (CST +8:00)",
  "Asia/Bangkok (ICT +7:00)",
  "Asia/Jakarta (WIB +7:00)",
  "Asia/Dubai (GST +4:00)",
  "Asia/Riyadh (AST +3:00)",
  "Africa/Nairobi (EAT +3:00)",
  "Africa/Lagos (WAT +1:00)",
  "Africa/Johannesburg (SAST +2:00)",
  "Europe/London (GMT +0:00)",
  "Europe/Berlin (CET +1:00)",
  "Europe/Paris (CET +1:00)",
  "Europe/Moscow (MSK +3:00)",
  "America/New_York (EST -5:00)",
  "America/Chicago (CST -6:00)",
  "America/Denver (MST -7:00)",
  "America/Los_Angeles (PST -8:00)",
  "America/Toronto (EST -5:00)",
  "America/Vancouver (PST -8:00)",
  "America/Sao_Paulo (BRT -3:00)",
  "America/Mexico_City (CST -6:00)",
  "Pacific/Auckland (NZST +12:00)",
  "Australia/Sydney (AEST +10:00)",
  "Australia/Melbourne (AEST +10:00)",
  "UTC (UTC +0:00)",
];

export const REGISTRATION_STEPS = ["Identity", "Profile", "Verification", "Consent"] as const;
